### ISSUE TITLE
How to customize error information

### ISSUE THREAD

**Issue by jingyuLin1999** [ajv-validator/ajv-i18n#210]
How to customize error information in schema？
like this:
```json
{
    "userName": {
      "type": "string",
      "minLength": 1,
      "require": true,
      "pattern": "\\d+_\\d+_\\d+",
      "message":"ERROR MESSAGE"
    },
}
```

**Comment by karlguillotte** [comment]
You can use https://github.com/ajv-validator/ajv-errors

**Comment by epoberezkin** [comment]
Thank you! Closing it.

**Comment by jingyuLin1999** [comment]
Thanks for you reply. it resolve my issue, however ajv-validator/ajv-errors have [the same issue](https://github.com/ajv-validator/ajv-i18n/issues/222#issue-1021547134) in  IE11. 
How to resolve it? 
Look forward to your reply.
