### ISSUE TITLE
Update for ajv 6.0.0 / draft-06/07

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv-i18n#75]
Only draft-07 "if/then/else" keyword
- [x] ar @Mahmoud-Mardeni
- [x] cz @kiskovacs
- [x] de @jmtoball
- [ ] fr @monlouisj
- [ ] nb @mtramm
- [ ] sk @kiskovacs
- [ ] sv @limmen

Both draft-06 and 07
(boolean schema, keywords "const", "contains", "propertyNames", "if/then/else")
- [ ] es
- [ ] hu (also some custom keywords)
- [ ] ja (also some custom keywords)
- [ ] pl
- [x] pt-BR

**Comment by Telokis** [comment]
Took the liberty to add the `if` translation for french: https://github.com/epoberezkin/ajv-i18n/pull/120

**Comment by Cerberooo** [comment]
Are there any plans to update this for usage with 7.0.0?

**Comment by epoberezkin** [comment]
Yes, early next year, but it mostly should work as all it does is iterating the errors. It won’t translate the new keywords of course, but it should work ok with draft-07 keywords.

**Comment by epoberezkin** [comment]
will open another issue with incomplete locales
